import type { SalonSculptSpec } from './types'

/** Unique anatomy / hair / outfit contracts for each cast member. */
export const SALON_SCULPT_SPECS: Record<string, SalonSculptSpec> = {
  aurelien: {
    id: 'aurelien',
    displayName: 'Aurélien',
    portraitUrl: '/salon-cast/aurelien.png',
    accent: '#d4a84b',
    accessory: 'glasses',
    headScale: 1.02,
    shoulderWidth: 1.12,
    torsoDepth: 1.05,
    hipWidth: 1.0,
    skin: '#c4a07a',
    hair: '#3a3834',
    suit: '#141218',
    shirt: '#efe6d8',
    shoe: '#0e0c0a',
    hairStyle: 'salt_pepper',
    outfit: 'tuxedo',
    build: 'masculine',
    hasBeard: true,
    faceCrop: { sx: 0.22, sy: 0.08, sw: 0.56, sh: 0.55 },
  },
  camille: {
    id: 'camille',
    displayName: 'Camille',
    portraitUrl: '/salon-cast/camille.png',
    accent: '#e0c06a',
    accessory: 'scarf',
    headScale: 0.96,
    shoulderWidth: 0.92,
    torsoDepth: 0.92,
    hipWidth: 1.05,
    skin: '#e8c4a8',
    hair: '#1a1210',
    suit: '#1a1218',
    shirt: '#f2ebe0',
    shoe: '#120e0c',
    hairStyle: 'updo',
    outfit: 'velvet_jacket',
    build: 'feminine',
    faceCrop: { sx: 0.24, sy: 0.1, sw: 0.52, sh: 0.52 },
  },
  hassan: {
    id: 'hassan',
    displayName: 'Hassan',
    portraitUrl: '/salon-cast/hassan.png',
    accent: '#c9a227',
    accessory: 'pin',
    headScale: 1.04,
    shoulderWidth: 1.15,
    torsoDepth: 1.08,
    hipWidth: 1.05,
    skin: '#5c3a28',
    hair: '#2a2824',
    suit: '#121016',
    shirt: '#f5f0e8',
    shoe: '#0a0806',
    hairStyle: 'cropped_beard',
    outfit: 'dinner_jacket',
    build: 'masculine',
    hasBeard: true,
    faceCrop: { sx: 0.22, sy: 0.1, sw: 0.56, sh: 0.54 },
  },
  ines: {
    id: 'ines',
    displayName: 'Inès',
    portraitUrl: '/salon-cast/ines.png',
    accent: '#d4a84b',
    accessory: 'bow',
    headScale: 0.95,
    shoulderWidth: 0.9,
    torsoDepth: 0.9,
    hipWidth: 0.98,
    skin: '#c6865a',
    hair: '#0a0806',
    suit: '#141018',
    shirt: '#1a1520',
    shoe: '#0e0c0a',
    hairStyle: 'bob',
    outfit: 'tuxedo',
    build: 'feminine',
    faceCrop: { sx: 0.24, sy: 0.1, sw: 0.52, sh: 0.52 },
  },
  julien: {
    id: 'julien',
    displayName: 'Julien',
    portraitUrl: '/salon-cast/julien.png',
    accent: '#b08d3e',
    accessory: 'pin',
    headScale: 1.0,
    shoulderWidth: 1.08,
    torsoDepth: 1.0,
    hipWidth: 0.98,
    skin: '#e0b896',
    hair: '#3b2a1c',
    suit: '#18141c',
    shirt: '#efe6d8',
    shoe: '#101010',
    hairStyle: 'short_slick',
    outfit: 'tuxedo',
    build: 'masculine',
    faceCrop: { sx: 0.22, sy: 0.08, sw: 0.56, sh: 0.55 },
  },
  lea: {
    id: 'lea',
    displayName: 'Léa',
    portraitUrl: '/salon-cast/lea.png',
    accent: '#e8c070',
    accessory: 'glasses',
    headScale: 0.97,
    shoulderWidth: 0.94,
    torsoDepth: 0.94,
    hipWidth: 1.02,
    skin: '#6b4028',
    hair: '#1c1410',
    suit: '#16121a',
    shirt: '#f5efe6',
    shoe: '#0e0c0a',
    hairStyle: 'natural_short',
    outfit: 'velvet_jacket',
    build: 'feminine',
    faceCrop: { sx: 0.24, sy: 0.1, sw: 0.52, sh: 0.52 },
  },
  marco: {
    id: 'marco',
    displayName: 'Marco',
    portraitUrl: '/salon-cast/marco.png',
    accent: '#c4a35a',
    accessory: 'bow',
    headScale: 1.03,
    shoulderWidth: 1.14,
    torsoDepth: 1.1,
    hipWidth: 1.08,
    skin: '#b07a55',
    hair: '#1a100c',
    suit: '#12141a',
    shirt: '#efe8dc',
    shoe: '#0c0a08',
    hairStyle: 'thick_dark',
    outfit: 'tuxedo',
    build: 'masculine',
    faceCrop: { sx: 0.22, sy: 0.08, sw: 0.56, sh: 0.54 },
  },
  nadege: {
    id: 'nadege',
    displayName: 'Nadège',
    portraitUrl: '/salon-cast/nadege.png',
    accent: '#d0b060',
    accessory: 'scarf',
    headScale: 0.98,
    shoulderWidth: 0.96,
    torsoDepth: 0.96,
    hipWidth: 1.08,
    skin: '#a86f45',
    hair: '#8a8880',
    suit: '#1a1218',
    shirt: '#efe6d8',
    shoe: '#100e0c',
    hairStyle: 'bun_silver',
    outfit: 'evening_dress',
    build: 'feminine',
    faceCrop: { sx: 0.24, sy: 0.1, sw: 0.52, sh: 0.52 },
  },
  olivier: {
    id: 'olivier',
    displayName: 'Olivier',
    portraitUrl: '/salon-cast/olivier.png',
    accent: '#b8974a',
    accessory: 'glasses',
    headScale: 1.01,
    shoulderWidth: 1.06,
    torsoDepth: 1.02,
    hipWidth: 1.02,
    skin: '#e8d0b8',
    hair: '#e8e4dc',
    suit: '#16141c',
    shirt: '#f5efe6',
    shoe: '#120e0a',
    hairStyle: 'white_short',
    outfit: 'tuxedo',
    build: 'masculine',
    faceCrop: { sx: 0.22, sy: 0.08, sw: 0.56, sh: 0.55 },
  },
  sofia: {
    id: 'sofia',
    displayName: 'Sofia',
    portraitUrl: '/salon-cast/sofia.png',
    accent: '#e0c06a',
    accessory: 'pin',
    headScale: 0.96,
    shoulderWidth: 0.93,
    torsoDepth: 0.92,
    hipWidth: 1.04,
    skin: '#c6865a',
    hair: '#0f0c0a',
    suit: '#1c1218',
    shirt: '#f0e8dc',
    shoe: '#0e0c0a',
    hairStyle: 'long_waves',
    outfit: 'velvet_jacket',
    build: 'feminine',
    faceCrop: { sx: 0.24, sy: 0.1, sw: 0.52, sh: 0.52 },
  },
}

export function salonSculptSpec(id: string): SalonSculptSpec {
  const spec = SALON_SCULPT_SPECS[id]
  if (!spec) {
    throw new Error(`Unknown salon sculpt id: ${id}`)
  }
  return spec
}
